<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Please enter Content Rule' => '@@@@',
  'Please upload an image' => '@@Si prega di caricare unimmagine@@',
  'Are you sure you want to delete this Contest ?' => 'Sei sicuro di voler eliminare questo concorso ?',
  'Entry description should not be empty' => 'Descrizione Evento non deve essere vuoto',
  'Entry title should not be empty' => 'Titolo di ingresso non deve essere vuoto',
  'Please accept terms and condition' => 'Si prega di accettare i termini e condizioni',
  'Please check atleast one checkBox' => 'Si prega di verificare, almeno una checkBox',
  'Please enter Content Description' => 'Inserisci Content Descrizione',
  'Please enter Contest Title' => 'Inserisci il concorso titolo',
  'Please enter Contest rule' => 'Inserisci regola Contest',
  'Please enter First Name' => 'Inserisci il nome',
  'Please enter Last Name' => 'Inserisci il Cognome',
  'Please enter Password' => 'Inserisci la password',
  'Please enter a valid date' => 'Si prega di inserire una data valida',
  'Please enter email id' => 'Inserisci ID e-mail',
  'Please enter end date' => 'Inserisci data di fine',
  'Please enter minor name' => 'Inserisci il nome del minore',
  'Please enter start date' => 'Inserisci data di inizio',
  'Please enter valid email id' => 'Inserisci ID e-mail valido',
  'Please upload banner image' => 'Si prega di caricare immagine del banner',
  'Please upload square image' => 'Si prega di caricare un\'immagine quadrata',
);
